name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    name:    build website
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install packages
        run:  npm ci

      - name: build
        run:  npm run build
        env:
          MENDELEY_ID:     ${{ secrets.MENDELEY_ID }}
          MENDELEY_SECRET: ${{ secrets.MENDELEY_SECRET }}

      - name: publish GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname:         digitallinguistics.io
          enable_jekyll: false
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          publish_dir:   ./docs
